language: ruby
rvm:
- 2.5.3


script: bundle exec jekyll build

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export AWS_ACCESS_KEY_ID=AKIA4QT3JUXZQ5FUEW7Z
  - export AWS_SECRET_ACCESS_KEY=$AWS_S3_SECRET_KEY

deploy:
  skip_cleanup: true
  provider: script
  script: aws s3 sync _site s3://cc2018.carpentrycon.org --delete
  on:
    branch: gh-pages
