url: http://www.carpentrycon.org
baseurl: "/"

# Site settings
title: CarpentryCon 2020
email: carpentrycon@carpentries.org
description: "The official website for CarpentryCon 2020"


# Team names, titles and social links
#people:
#- name: Jonah Duckles
#  pic: 1
#  position: Executive Director
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #
#
#- name: Belinda Weaver
#  pic: 2
#  position: Community Development Lead
#  social:
#    - title: twitter
#      url: https://twitter.com/cloudaus
#    - title: github
#      url: https://github.com/weaverbel
#
#- name: Maneesha Sane
#  pic: 3
#  position: Workshop Administrator
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/thecarpentries
  - title: github
    url: https://github.com/carpentries/
  - title: facebook
    url: https://www.facebook.com/carpentries/
  - title: slack
    url: https://swc-slack-invite.herokuapp.com/

# Postal address (add as many lines as necessary)
#address:
#  - line: Brisbane, Australia

# Build settings
markdown: kramdown
permalink: pretty
